anguage: android
sudo: false
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-android-m2repository
script: './gradlew build check'
before_install:
- openssl aes-256-cbc -K $encrypted_69044bd0f1e4_key -iv $encrypted_69044bd0f1e4_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
deploy:
  provider: releases
  api_key:
  secure: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQClnAkKJTOooSgaBmd1Hp+uaBWY8fgYPbs44GiK2xpeAA1tFvOU7bIognNJ4jcoqNpPxiJTsf2PUL+UOEMiGX6SDsrYDsvNNUm7OUhAHwn16FHPzytICclZ6ohGD0vZEjL6aocC2MZK9lnNgWuHCSWD6q3Q4eXauIAN7fW1HW0V/sVX63jw2lWpohGtdirDRSaRoU+komMZRKLV6q+UbXZoGjTontAFvFITfTFw3/0qNkPaji3JrQjLNLaqPAKamrbKI7ErUwz/Hmcc1y/qcAcT+7qGUhZCeFlxogrCM31AVC6YAnZnubGfRw92nXhOwBGzju9M7GixZZkzpHNqiig+/O4iTZcEBJNAUi2GGKkjvzQRkmFhccz/wfQ4UG7QrUAnQDuFQTqfguqNfzX17KI3mjCKadxbm5UAhvgbWpkLvoKSOGwbI6ayFNfdiKbLOn5/saKvI5kMLWcWg6kxaRj6Y+QsLPoSLIo8e/cBLsaxg7sgh55n4668RJVRSgGTAMio85kWvt+WmBBzkzyNjajCLmKFgdjS6/a52xgr1wIKNXevN4y//NW3y0Hf70YJDiNwRjz1P4aRRdhUObOg/iuNuxppKfIZzMspr1uVI1G83pF/jfZm3v41vXkasOdTy/YN7mNZaC5/LSmgFBi2VLDd9VrsBP6igjsnBwis7ydMqQ== 
  file: app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    repo: chinuayu/easypermissions
    tags: true