anguage: android
sudo: false
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-android-m2repository
script: './gradlew build check'
before_install:
- openssl aes-256-cbc -K $encrypted_69044bd0f1e4_key -iv $encrypted_69044bd0f1e4_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
deploy:
  provider: releases
  api_key:
  secure: dfa623736c18814fd37f3d38d4baafcc6e2e9f09
  file: app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    repo: chinuayu/easypermissions
    tags: true