language: android
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
   - tools
   - build-tools-24.0.0
   - android-24
   - extra-android-support
   - extra-google-google_play_services
   - extra-android-m2repository
   - extra-google-m2repository
   - addon-google_apis-google-24

before_script: echo y | ${ANDROID_HOME}tools/bin/sdkmanager --channel=3 "tools" "platform-tools" "platforms;android-27"
script: ./gradlew build

after_failure:
  - cat app/build/reports/tests/testDebugUnitTest/index.html

after_success:
   - chmod +x ./upload-gh-pages.sh
   - ./upload-apk.sh
